---
include:
- board: nice_nano//zmk
  shield: settings_reset
- board: xiao_ble//zmk
  shield: settings_reset

- board: xiao_ble//zmk
  shield: charybdis_dongle_prospector prospector_adapter
- board: nice_nano//zmk
  shield: charybdis_central_right
- board: nice_nano//zmk
  shield: charybdis_peripheral_left
- board: nice_nano//zmk
  shield: charybdis_peripheral_right

- board: nice_nano//zmk
  shield: lapka_dongle
- board: xiao_ble//zmk
  shield: lapka_dongle
- board: xiao_ble//zmk
  shield: lapka_dongle_prospector prospector_adapter
- board: nice_nano//zmk
  shield: lapka_central_left
- board: nice_nano//zmk
  shield: lapka_peripheral_left
- board: nice_nano//zmk
  shield: lapka_peripheral_right

- board: nice_nano//zmk
  shield: tester_pro_micro
  format: bt
