---
include:
- board: nice_nano
  shield: settings_reset
- board: xiao_ble
  shield: settings_reset

- board: nice_nano
  shield: corne_dongle
  cmake-args: -DCONFIG_ZMK_SLEEP=n
- board: nice_nano
  shield: corne_central_left
- board: nice_nano
  shield: corne_peripheral_left
- board: nice_nano
  shield: corne_peripheral_right

# - board: xiao_ble
  # shield: totem_dongle dongle_screen
  # cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME="TotemDongle" -DCONFIG_ZMK_SLEEP=n
- board: xiao_ble
  shield: totem_dongle prospector_adapter
  cmake-args: -DCONFIG_ZMK_SLEEP=n
- board: xiao_ble
  shield: totem_central_left
- board: xiao_ble
  shield: totem_peripheral_left
- board: xiao_ble
  shield: totem_peripheral_right
