---
include:
- board: nice_nano
  shield: settings_reset
- board: xiao_ble
  shield: settings_reset

- board: nice_nano
  shield: corne_dongle
- board: nice_nano
  shield: corne_central_left
- board: nice_nano
  shield: corne_peripheral_left
- board: nice_nano
  shield: corne_peripheral_right

- board: xiao_ble
  shield: totem_dongle prospector_adapter
- board: xiao_ble
  shield: totem_dongle
- board: xiao_ble
  shield: totem_central_left
- board: xiao_ble
  shield: totem_peripheral_left
- board: xiao_ble
  shield: totem_peripheral_right

- board: xiao_ble
  shield: charybdis_dongle prospector_adapter
- board: nice_nano
  shield: charybdis_central_right
- board: nice_nano
  shield: charybdis_peripheral_left
- board: nice_nano
  shield: charybdis_peripheral_right
