---
include:
- board: nice_nano_v2
  shield: settings_reset
- board: seeeduino_xiao_ble
  shield: settings_reset

- board: seeeduino_xiao_ble
  shield: corne_central_dongle
  cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME="XiaoCorneDongle" -DCONFIG_ZMK_SLEEP=n
- board: nice_nano_v2
  shield: corne_central_dongle
  cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME="NiceCorneDongle" -DCONFIG_ZMK_SLEEP=n
- board: nice_nano_v2
  shield: corne_central_left
  cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME="NiceCorne"
- board: nice_nano_v2
  shield: corne_peripheral_left
- board: nice_nano_v2
  shield: corne_peripheral_right
