---
include:
- board: nice_nano//zmk
  shield: settings_reset
- board: xiao_ble//zmk
  shield: settings_reset

- board: nice_nano//zmk
  shield: corne_dongle
- board: nice_nano//zmk
  shield: corne_central_left
- board: nice_nano//zmk
  shield: corne_peripheral_left
- board: nice_nano//zmk
  shield: corne_peripheral_right

- board: nice_nano//zmk
  shield: totem_dongle
- board: nice_nano//zmk
  shield: totem_dongle_oled_32 dongle_display
- board: nice_nano//zmk
  shield: totem_dongle_oled_64 dongle_display
- board: xiao_ble//zmk
  shield: totem_dongle
- board: xiao_ble//zmk
  shield: totem_dongle_prospector prospector_adapter
- board: xiao_ble//zmk
  shield: totem_central_left
- board: xiao_ble//zmk
  shield: totem_peripheral_left
- board: xiao_ble//zmk
  shield: totem_peripheral_right

- board: xiao_ble//zmk
  shield: charybdis_dongle_prospector prospector_adapter
- board: nice_nano//zmk
  shield: charybdis_central_right
- board: nice_nano//zmk
  shield: charybdis_peripheral_left
- board: nice_nano//zmk
  shield: charybdis_peripheral_right
